# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

platform :ios do

  lane :release do
    projectPath = "./Test64.xcodeproj"
    increment_build_number(     
      xcodeproj: projectPath
    )    
    version = get_version_number(
      xcodeproj: projectPath,
      target: "Test64"
    )
    build = get_build_number(
      xcodeproj: projectPath
    )
    build_app(
      scheme: "Test64",
      workspace: "./Test64.xcworkspace",
      include_bitcode: true,
      clean: true,
      export_method: "app-store",
      output_directory: "./build/iOS/",
      output_name: "Test64_#{version}_#{build}.ipa"
    )
  end
end
