# The name of our workflow
name: Build

on: 
  # Trigger on every pull request and on push
  # to the `main` branch.
  pull_request:
  push:
    branches:
      - master
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - run: | 
          echo "${{ secrets.RELEASE_KEYSTORE }}" > release.keystore.asc
          gpg -d --passphrase "${{ secrets.PASSPHRASE }}" --batch release.keystore.asc > android/fastlane/release.keystore
          
      - run: yarn install
      
      - uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'android release'
          subdirectory: 'android'
          options: '{ "RELEASE_KEYSTORE_PASSWORD": "${{secrets.RELEASE_KEYSTORE_PASSWORD}}", "RELEASE_KEYSTORE_KEY_PASSWORD": "${{secrets.RELEASE_KEYSTORE_KEY_PASSWORD}}", "RELEASE_KEYSTORE_ALIAS": "${{secrets.RELEASE_KEYSTORE_ALIAS}}" }'
        
      - uses: actions/upload-artifact@v2
        with:
          name: releaseDevBuild
          path: android/app/build/outputs/apk/release/app-release.apk
