# The name of our workflow
name: Build

on: 
  # Trigger on every pull request and on push
  # to the `main` branch.
  pull_request:
  push:
    branches:
      - master
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - run: | 
          echo "${{ secrets.RELEASE_KEYSTORE }}" > release.keystore.asc
          gpg -d --passphrase "${{ secrets.PASSPHRASE }}" --batch release.keystore.asc > android/fastlane/release.keystore
          
      - name: Install packages
        run: yarn install
        
      - run: cd android && ./gradlew assembleDebug
        
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: android/app/build/outputs/apk/debug/app-debug.apk
