# This is a basic workflow to help you get started with Actions

name: iOSAdHoc

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-11

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - run: |
          yarn install
          cd ios
          pod install
      
      - name: iOS Build Action
        uses: yukiarrr/ios-build-action@v1.4.0
        with:
          project-path: ./ios/Test64.xcodeproj
          workspace-path: ./ios/Test64.xcworkspace # optional
          p12-base64: ${{ secrets.P12_BASE64 }}
          certificate-password: ${{ secrets.IOS_P12_PASSWORD }}
          mobileprovision-base64: ${{ secrets.AD_HOC_PROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGN_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
          export-method: "ad-hoc"
          
      - uses: actions/upload-artifact@v2
        with:
          name: AdHocDevBuild
          path: ./output.ipa

